-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-01 13:39:54 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE giro (
    nomor_rekening CHAR(20) NOT NULL,
    no_buku_cek    INTEGER NOT NULL
);

ALTER TABLE giro ADD CONSTRAINT giro_pk PRIMARY KEY ( nomor_rekening );

CREATE TABLE karyawan (
    id_karyawan          CHAR(20) NOT NULL,
    nama                 VARCHAR2(50) NOT NULL,
    alamat               VARCHAR2(50) NOT NULL,
    jabatan              VARCHAR2(50) NOT NULL,
    no_telpon            CHAR(12) NOT NULL,
    gaji                 NUMBER NOT NULL,
    karyawan_id_karyawan CHAR(20)
);

ALTER TABLE karyawan ADD CONSTRAINT karyawan_pk PRIMARY KEY ( id_karyawan );

CREATE TABLE layanan (
    id_layanan              CHAR(20) NOT NULL,
    jumlah                  NUMBER NOT NULL,
    rekening_nomor_rekening CHAR(20) NOT NULL,
    karyawan_id_karyawan    CHAR(20) NOT NULL,
    penarikan_id_penarikan  CHAR(10),
    setoran_id_setoran      CHAR(10)
);

ALTER TABLE layanan
    ADD CONSTRAINT arc_2 CHECK ( ( ( penarikan_id_penarikan IS NOT NULL )
                                   AND ( setoran_id_setoran IS NULL ) )
                                 OR ( ( setoran_id_setoran IS NOT NULL )
                                      AND ( penarikan_id_penarikan IS NULL ) )
                                 OR ( ( penarikan_id_penarikan IS NULL )
                                      AND ( setoran_id_setoran IS NULL ) ) );

CREATE UNIQUE INDEX layanan__idx ON
    layanan (
        penarikan_id_penarikan
    ASC );

CREATE UNIQUE INDEX layanan__idxv1 ON
    layanan (
        setoran_id_setoran
    ASC );

ALTER TABLE layanan ADD CONSTRAINT layanan_pk PRIMARY KEY ( id_layanan );

CREATE TABLE nasabah (
    id_nasabah   CHAR(10) NOT NULL,
    nama         VARCHAR2(50) NOT NULL,
    alamat       VARCHAR2(100) NOT NULL,
    nomor_telpon CHAR(12) NOT NULL,
    pin          CHAR(6) NOT NULL
);

ALTER TABLE nasabah ADD CONSTRAINT nasabah_pk PRIMARY KEY ( id_nasabah );

CREATE TABLE penarikan (
    id_penarikan       CHAR(10) NOT NULL,
    jumlah             NUMBER NOT NULL,
    layanan_id_layanan CHAR(20),
    sisa_saldo         VARCHAR2(100) NOT NULL
);

CREATE UNIQUE INDEX penarikan__idx ON
    penarikan (
        layanan_id_layanan
    ASC );

ALTER TABLE penarikan ADD CONSTRAINT penarikan_pk PRIMARY KEY ( id_penarikan );

CREATE TABLE rekening (
    nomor_rekening       CHAR(20) NOT NULL,
    saldo                NUMBER NOT NULL,
    karyawan_id_karyawan CHAR(20) NOT NULL,
    nasabah_id_nasabah   CHAR(10) NOT NULL
);

ALTER TABLE rekening ADD CONSTRAINT rekening_pk PRIMARY KEY ( nomor_rekening );

CREATE TABLE riwayat_transaksi (
    id_transaksi       CHAR(20) NOT NULL,
    tanggal_transaksi  DATE NOT NULL,
    jumlah_transaksi   INTEGER NOT NULL,
    layanan_id_layanan CHAR(20) NOT NULL,
    nasabah_id_nasabah CHAR(10) NOT NULL
);

ALTER TABLE riwayat_transaksi ADD CONSTRAINT riwayat_transaksi_pk PRIMARY KEY ( id_transaksi );

CREATE TABLE setoran (
    id_setoran         CHAR(10) NOT NULL,
    jumlah             NUMBER NOT NULL,
    layanan_id_layanan CHAR(20),
    saldo_awal         INTEGER NOT NULL,
    saldo_akhir        INTEGER NOT NULL
);

CREATE UNIQUE INDEX setoran__idx ON
    setoran (
        layanan_id_layanan
    ASC );

ALTER TABLE setoran ADD CONSTRAINT setoran_pk PRIMARY KEY ( id_setoran );

CREATE TABLE tabungan (
    nomor_rekening CHAR(20) NOT NULL,
    bunga          NUMBER NOT NULL
);

ALTER TABLE tabungan ADD CONSTRAINT tabungan_pk PRIMARY KEY ( nomor_rekening );

ALTER TABLE giro
    ADD CONSTRAINT giro_rekening_fk FOREIGN KEY ( nomor_rekening )
        REFERENCES rekening ( nomor_rekening );

ALTER TABLE karyawan
    ADD CONSTRAINT karyawan_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE layanan
    ADD CONSTRAINT layanan_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE layanan
    ADD CONSTRAINT layanan_penarikan_fk FOREIGN KEY ( penarikan_id_penarikan )
        REFERENCES penarikan ( id_penarikan )
            ON DELETE CASCADE;

ALTER TABLE layanan
    ADD CONSTRAINT layanan_rekening_fk FOREIGN KEY ( rekening_nomor_rekening )
        REFERENCES rekening ( nomor_rekening )
            ON DELETE CASCADE;

ALTER TABLE layanan
    ADD CONSTRAINT layanan_setoran_fk FOREIGN KEY ( setoran_id_setoran )
        REFERENCES setoran ( id_setoran )
            ON DELETE CASCADE;

ALTER TABLE penarikan
    ADD CONSTRAINT penarikan_layanan_fk FOREIGN KEY ( layanan_id_layanan )
        REFERENCES layanan ( id_layanan )
            ON DELETE CASCADE;

ALTER TABLE rekening
    ADD CONSTRAINT rekening_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE rekening
    ADD CONSTRAINT rekening_nasabah_fk FOREIGN KEY ( nasabah_id_nasabah )
        REFERENCES nasabah ( id_nasabah )
            ON DELETE CASCADE;

ALTER TABLE riwayat_transaksi
    ADD CONSTRAINT riwayat_transaksi_layanan_fk FOREIGN KEY ( layanan_id_layanan )
        REFERENCES layanan ( id_layanan )
            ON DELETE CASCADE;

ALTER TABLE riwayat_transaksi
    ADD CONSTRAINT riwayat_transaksi_nasabah_fk FOREIGN KEY ( nasabah_id_nasabah )
        REFERENCES nasabah ( id_nasabah );

ALTER TABLE setoran
    ADD CONSTRAINT setoran_layanan_fk FOREIGN KEY ( layanan_id_layanan )
        REFERENCES layanan ( id_layanan )
            ON DELETE CASCADE;

ALTER TABLE tabungan
    ADD CONSTRAINT tabungan_rekening_fk FOREIGN KEY ( nomor_rekening )
        REFERENCES rekening ( nomor_rekening );

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             4
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
